export {
  EXERCISES,
  getExerciseById,
  searchExercises,
  type ExerciseSearchFilters,
} from "./catalog.ts";
export {
  CASELOAD_SEED_TIMESTAMP,
  DEFAULT_SYNTHETIC_CLIENT_ID,
  SYNTHETIC_CLIENTS,
  cloneCaseloadStore,
  cloneProgramRecord,
  cloneWorkspaceSnapshot,
  createSeedCaseload,
  getSyntheticClient,
  programStatusFromWorkspace,
  type ProgramStatus,
  type SyntheticClient,
  type TherapistCaseloadStore,
  type TherapistProgramRecord,
  type TherapistWorkspaceSnapshot,
} from "./caseload.ts";
export {
  EXERCISE_DOSAGE_LIMITS,
  confirmProgram,
  createProgramDraft,
  estimateProgramDuration,
  validateCaseContext,
  validateDraft,
  type ConfirmProgramRequest,
  type CreateProgramDraftInput,
  type DomainFactories,
  type DraftValidationConstraints,
  type DraftValidationSummary,
  type ExerciseDosageLimits,
  type NumericRange,
} from "./program.ts";
export {
  PAIN_SAFETY_THRESHOLD,
  completeMotionSetCheckIn,
  completeExerciseSet,
  createPatientSession,
  finishSession,
  getSessionProgress,
  logPain,
  pauseSession,
  resumeSession,
  skipExercise,
  stageMotionSetResult,
  startExerciseSet,
  stopSession,
  switchActiveCameraSetToManualFallback,
} from "./session.ts";
export {
  projectLatestPatientMotionResult,
  type PatientCompletedMotionSetView,
  type PatientMotionContinuationBlock,
} from "./patient-motion-view.ts";
export type {
  CompleteMotionSetCheckInInput,
  CompleteExerciseSetInput,
  LogPainInput,
  PainEvent,
  PainSafetyGate,
  PartialSetResultInput,
  PatientExerciseSet,
  PatientMotionAttempt,
  PatientProgramSnapshot,
  PatientSession,
  PatientSessionProgress,
  PatientSessionStatus,
  PatientSessionSummary,
  PatientSetMode,
  PatientSetStatus,
  PrescribedSetTarget,
  SessionFactories,
  SessionIdKind,
  SetActualCompletion,
  SetCompletionKind,
  SkipExerciseInput,
  StageMotionSetResultInput,
  StartExerciseSetInput,
  StopSessionInput,
  SwitchActiveCameraSetToManualFallbackInput,
} from "./session-types.ts";
export type {
  ActivityActor,
  AgentActivity,
  BodyRegion,
  CaseContext,
  CoachingMode,
  ConfirmedProgram,
  Difficulty,
  DomainError,
  DomainResult,
  Exercise,
  ExerciseDosage,
  ProgramDraft,
  ProgramItem,
  ReviewStatus,
} from "./types.ts";
