export {
  EXERCISES,
  getExerciseById,
  searchExercises,
  type ExerciseSearchFilters,
} from "./catalog.ts";
export {
  CASELOAD_SEED_TIMESTAMP,
  DEFAULT_SYNTHETIC_CLIENT_ID,
  SYNTHETIC_CLIENTS,
  cloneCaseloadStore,
  cloneProgramRecord,
  cloneWorkspaceSnapshot,
  createSeedCaseload,
  getSyntheticClient,
  programStatusFromWorkspace,
  type ProgramStatus,
  type SyntheticClient,
  type TherapistCaseloadStore,
  type TherapistProgramRecord,
  type TherapistWorkspaceSnapshot,
} from "./caseload.ts";
export {
  EXERCISE_DOSAGE_LIMITS,
  confirmProgram,
  createProgramDraft,
  estimateProgramDuration,
  validateCaseContext,
  validateDraft,
  type ConfirmProgramRequest,
  type CreateProgramDraftInput,
  type DomainFactories,
  type DraftValidationConstraints,
  type DraftValidationSummary,
  type ExerciseDosageLimits,
  type NumericRange,
} from "./program.ts";
export {
  prepareProgramDraftContext,
  type DraftContextSearchRequest,
  type PrepareProgramDraftContextInput,
  type PreparedDraftMovement,
  type PreparedProgramDraftContext,
} from "./draft-context.ts";
export {
  MAX_COACHING_FOCUS_TEXT_LENGTH,
  PAIN_SAFETY_THRESHOLD,
  acceptNextSetFocus,
  completeMotionSetCheckIn,
  completeExerciseSet,
  createPatientSession,
  dismissNextSetFocus,
  finishSession,
  getSessionProgress,
  logPain,
  pauseSession,
  resumeSession,
  skipExercise,
  stageNextSetFocus,
  stageMotionSetResult,
  startExerciseSet,
  stopSession,
  switchActiveCameraSetToManualFallback,
} from "./session.ts";
export {
  projectLatestPatientMotionResult,
  type PatientCompletedMotionSetView,
  type PatientMotionContinuationBlock,
} from "./patient-motion-view.ts";
export {
  MAX_ADHERENCE_DEVIATION_ROWS,
  projectAdherenceSummary,
  type AdherenceDeviationRow,
  type AdherenceDeviationStatus,
  type AdherenceSummaryView,
} from "./adherence-view.ts";
export type {
  DecideNextSetFocusInput,
  CompleteMotionSetCheckInInput,
  CompleteExerciseSetInput,
  LogPainInput,
  PainEvent,
  PainSafetyGate,
  PatientCoachingEvidenceCode,
  PatientCoachingFocus,
  PatientCoachingFocusStatus,
  PartialSetResultInput,
  PatientExerciseSet,
  PatientMotionAttempt,
  PatientProgramSnapshot,
  PatientSession,
  PatientSessionProgress,
  PatientSessionStatus,
  PatientSessionSummary,
  PatientSetMode,
  PatientSetStatus,
  PrescribedSetTarget,
  SessionFactories,
  SessionIdKind,
  SetActualCompletion,
  SetCompletionKind,
  SkipExerciseInput,
  StageNextSetFocusInput,
  StageMotionSetResultInput,
  StartExerciseSetInput,
  StopSessionInput,
  SwitchActiveCameraSetToManualFallbackInput,
} from "./session-types.ts";
export type {
  ActivityActor,
  AgentActivity,
  BodyRegion,
  CaseContext,
  CoachingMode,
  ConfirmedProgram,
  Difficulty,
  DomainError,
  DomainResult,
  Exercise,
  ExerciseDosage,
  ProgramDraft,
  ProgramItem,
  ReviewStatus,
} from "./types.ts";
