export {
  EXERCISES,
  getExerciseById,
  searchExercises,
  type ExerciseSearchFilters,
} from "./catalog.ts";
export {
  EXERCISE_DOSAGE_LIMITS,
  confirmProgram,
  createProgramDraft,
  estimateProgramDuration,
  validateCaseContext,
  validateDraft,
  type ConfirmProgramRequest,
  type CreateProgramDraftInput,
  type DomainFactories,
  type DraftValidationConstraints,
  type DraftValidationSummary,
  type ExerciseDosageLimits,
  type NumericRange,
} from "./program.ts";
export {
  PAIN_SAFETY_THRESHOLD,
  completeExerciseSet,
  createPatientSession,
  finishSession,
  getSessionProgress,
  logPain,
  pauseSession,
  resumeSession,
  skipExercise,
  startExerciseSet,
  stopSession,
} from "./session.ts";
export type {
  CompleteExerciseSetInput,
  LogPainInput,
  PainEvent,
  PainSafetyGate,
  PartialSetResultInput,
  PatientExerciseSet,
  PatientProgramSnapshot,
  PatientSession,
  PatientSessionProgress,
  PatientSessionStatus,
  PatientSessionSummary,
  PatientSetMode,
  PatientSetStatus,
  PrescribedSetTarget,
  SessionFactories,
  SessionIdKind,
  SetActualCompletion,
  SetCompletionKind,
  SkipExerciseInput,
  StartExerciseSetInput,
  StopSessionInput,
} from "./session-types.ts";
export type {
  ActivityActor,
  AgentActivity,
  BodyRegion,
  CaseContext,
  CoachingMode,
  ConfirmedProgram,
  Difficulty,
  DomainError,
  DomainResult,
  Exercise,
  ExerciseDosage,
  ProgramDraft,
  ProgramItem,
  ReviewStatus,
} from "./types.ts";
